# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a807b92ae85a59d4537b244a3e08bfd9fb053f628061a56515d74ddc18200a0e228831d2e72ea3783ad108cd4111aa52949072bb1d96b8db0cb88f053fec4a8f

test:
  secret_key_base: a2af3e48783a579736b427ddb8919d02aa80020457491d51d2416320e15f46039b10753fd9a0482a494ea18efcdaf4247ea97fcd813e0f29f1fe7cefbebae3c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
